/**
 * Created by OXOYO on 2017/6/26.
 */

export const PLATFORM_SIGN_IN_SUCCESS = 'PLATFORM_SIGN_IN_SUCCESS'
export const PLATFORM_SIGN_IN_FAIL = 'PLATFORM_SIGN_IN_FAIL'
export const PLATFORM_SIGN_OUT_SUCCESS = 'PLATFORM_SIGN_OUT_SUCCESS'
export const PLATFORM_SIGN_OUT_FAIL = 'PLATFORM_SIGN_OUT_FAIL'
